name: release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'yarn.lock'
      - 'envsubst-react-environment.sh'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: release
        uses: anothrNick/github-tag-action@1.35.0
        env:
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: react-nginx-auto-discover-vars
          push: true
          tags: |
            rafaelcalleja/react-app-hello-world:${{ steps.release.outputs.tag }}
            rafaelcalleja/react-app-hello-world:latest
